### ISSUE TITLE
Collisions in set of values around 77K items

### ISSUE THREAD

**Issue by jgoux** [oftherivier/fictional#29]
A user of `@snaplet/copycat` reported collisions in the `uuid` method.

After digging up a bit, it seems like the `string-hash` library is indeed limited in the number of outputs it can produce (between 0 and 4294967295), so collisions are expected around ~77K inputs [according to the author.](https://github.com/darkskyapp/string-hash/issues/10#issuecomment-422020290)

The recommendation is to stick to md5 for large datasets.

I'm not sure about the scope of the change, but the one I see would be to drop `string-hash` to generate a hash and just return the `md5` value, so changing the lines [here](https://github.com/oftherivier/fictional/blob/master/hash.js#L15-L17) to:

```ts
function hash(input) {
  return md5(stringify(input) + hash.salt)
}
```

I don't have the full scope and if this change would have any side-effect. 😅 

Here is a repro: https://replit.com/@jgoux/VillainousUnacceptableFactorial#index.mjs (in the Shell on the right run `node index.mjs`)

**Comment by justinvdm** [comment]
Should be solved in `0.5.0`! 🤞  https://github.com/oftherivier/fictional/blob/master/CHANGELOG.md#050-2022-09-19
